# Generated by Django 5.0.7 on 2024-07-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_usermember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category1',
        ),
    ]
